version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "requirements: "
    open-pull-requests-limit: 15
  - package-ecosystem: "npm"
    directories:
      - "www/**"
    commit-message:
      prefix: "www: "
    # more PRs won't help due to merge conflicts in lock file
    open-pull-requests-limit: 3
  - package-ecosystem: "npm"
    directories:
      - "e2e/**"
    commit-message:
      prefix: "e2e: "
    # more PRs won't help due to merge conflicts in lock file
    open-pull-requests-limit: 3
  - package-ecosystem: "docker"
    directories:
      - "**/*"
    commit-message:
      prefix: "docker: "
    open-pull-requests-limit: 15
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "github: "
